changelog:
  exclude:
    labels:
      - release
      - documentation
      - packages
      - repository
  categories:
    - title: New Features
      labels:
        - feature
    - title: Bug Fixes
      labels:
        - bug
    - title: Updates
      labels:
        - update
    - title: Other Changes
      labels:
        - "*"
