exclude-labels:
  - 'documentation'
  - 'failed'
  - 'github-actions'
  - 'packages'
  - 'release'
  - 'repository'
  - 'refactoring'
  - 'tests'
categories:
  - title: 'New Features'
    label: 'feature'
  - title: 'Bug Fixes'
    label: 'bugfix'
  - title: 'Other Changes'
    label: 'update'
change-template: '- $TITLE (#$NUMBER)'
template: |
  # Changelog

  $CHANGES
