ignore:
  - "source/EduCATS/App.cs"
  - "source/EduCATS/Controls"
  - "source/EduCATS/Pages"
  - "source/EduCATS/Helpers/Forms"
  - "source/EduCATS/Themes/Templates"
  - "**/Models/**/*"
comment:
  layout: "reach, diff"
  behavior: new
  require_changes: false
  require_base: no
  require_head: yes
  branches:
    - "master"
    - "develop"
