name: build

on: [ workflow_dispatch, pull_request ]
  
env:
  COVERAGE_COVERAGE_FILE_PATH: ./coverage/lcov.info

jobs:
  test:
    runs-on: macos-latest
    environment: github-actions-release
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unit-Tests Build + Coverlet
        run: |
          dotnet tool install --global coverlet.console
          dotnet add $PROJECT_PATH package coverlet.collector
          dotnet build $PROJECT_PATH
          dotnet test --collect:"XPlat Code Coverage" --settings $COVERLET_SETTINGS --results-directory:"$COVERAGE_DIRECTORY" $PROJECT_PATH
          mv $COVERAGE_DIRECTORY/*/$COVERAGE_INFO_FILENAME ${{ env.COVERAGE_COVERAGE_FILE_PATH }}
        env:
          PROJECT_PATH: ./source/EduCATS.UnitTests/EduCATS.UnitTests.csproj
          COVERLET_SETTINGS: ./source/coverlet.runsettings
          COVERAGE_DIRECTORY: ./coverage
          COVERAGE_INFO_FILENAME: coverage.info          
        
      - name: Codecov Deploy
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{ env.COVERAGE_COVERAGE_FILE_PATH }}
          os: macos

  build:
    runs-on: macos-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Restore NuGet packages
        run: nuget restore $SOLUTION_PATH
        env:
          SOLUTION_PATH: ./source/EduCATS.sln
        
      - name: Build iOS        
        run: MSBuild /t:Build /p:Configuration=$CONFIGURATION /p:Platform=$PLATFORM $PROJECT_PATH
        env:
          CONFIGURATION: Release
          PLATFORM: iPhoneSimulator
          PROJECT_PATH: ./source/EduCATS.iOS/EduCATS.iOS.csproj
          
      - name: Build Android
        run: MSBuild /t:Build /p:Configuration=$CONFIGURATION $PROJECT_PATH
        env:
          CONFIGURATION: Release
          PROJECT_PATH: ./source/EduCATS.Android/EduCATS.Android.csproj
