name: build

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Restore NuGet packages
        run: nuget restore ./source/EduCATS.sln
        
      - name: Build iOS        
        run: MSBuild /t:Build /p:Configuration=Release /p:Platform=iPhoneSimulator ./source/EduCATS.iOS/EduCATS.iOS.csproj              
      
      - name: Build Android
        run: MSBuild /t:Build /p:Configuration=Release ./source/EduCATS.Android/EduCATS.Android.csproj
