name: release

on: [ push ]
#  push:
#    branches: [ master ]

#   workflow_dispatch:
  
env:
  APP_VERSION: 2.2.5
  ARTIFACTS_DIRECTORY: ./artifacts
  ARTIFACTS_IPA_PATH: ./artifacts/EduCATS.ipa
  ARTIFACTS_APK_PATH: ./artifacts/by.bntu.educats.apk
  ARTIFACTS_AAB_PATH: ./artifacts/by.bntu.educats.aab
  COVERAGE_COVERAGE_FILE_PATH: ./coverage/lcov.info
  SOLUTION_PATH: ./source/EduCATS.sln

jobs:
  setup:
    runs-on: macos-latest
    environment: github-actions-release

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: NuGet Restore
        run: nuget restore ${{ env.SOLUTION_PATH }}
          
      - name: NuGet Cache
        id: nuget-cache
        uses: actions/cache@v3.0.3
        with:
          path: |
            $CACHE_DIRECTORY
            $OBJ_DIRECTORY_FORMS
            $OBJ_DIRECTORY_IOS
            $OBJ_DIRECTORY_ANDROID
          key: ${{ runner.os }}-nuget
        env:
          CACHE_DIRECTORY: ~/.nuget/packages
          OBJ_DIRECTORY_FORMS: ./source/EduCATS/obj
          OBJ_DIRECTORY_IOS: ./source/EduCATS.iOS/obj
          OBJ_DIRECTORY_ANDROID: ./source/EduCATS.Android/obj
          
  test:
    runs-on: macos-latest
    environment: github-actions-release
    needs: setup
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - if: ${{ steps.nuget-cache.outputs.cache-hit == 'false' }}
        name: NuGet Restore
        run: nuget restore ${{ env.SOLUTION_PATH }}
    
      - name: Unit-Tests Build + Coverlet
        run: |
          dotnet tool install --global coverlet.console
          dotnet add $PROJECT_PATH package coverlet.collector
          dotnet build $PROJECT_PATH
          dotnet test --collect:"XPlat Code Coverage" --settings $COVERLET_SETTINGS --results-directory:"$COVERAGE_DIRECTORY" $PROJECT_PATH
          mv $COVERAGE_DIRECTORY/*/$COVERAGE_INFO_FILENAME ${{ env.COVERAGE_COVERAGE_FILE_PATH }}
        env:
          PROJECT_PATH: ./source/EduCATS.UnitTests/EduCATS.UnitTests.csproj
          COVERLET_SETTINGS: ./source/coverlet.runsettings
          COVERAGE_DIRECTORY: ./coverage
          COVERAGE_INFO_FILENAME: coverage.info          
        
      - name: Codecov Deploy
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{ env.COVERAGE_COVERAGE_FILE_PATH }}
          os: macos
          
  build:
    runs-on: macos-latest
    environment: github-actions-release
    needs: test
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - if: ${{ steps.nuget-cache.outputs.cache-hit == 'false' }}
        name: NuGet Restore
        run: nuget restore ${{ env.SOLUTION_PATH }}
        
      - name: iOS Certificates Install
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.IOS_CERTIFICATE_APPSTORE }}
          p12-password: ${{ secrets.IOS_CERTIFICATE_APPSTORE_PASSWORD }}
          keychain: github-actions-xamarin
          keychain-password: ''
      
      - name: iOS Provisioning Profiles Install
        uses: akiojin/install-provisioning-profile-github-action@v1.0
        with:
          base64: ${{ secrets.IOS_PROVISIONING_PROFILE_APPSTORE }}
          
      - name: Android Signing Setup
        run: (echo ${{ secrets.ANDROID_KEYSTORE_FILE }} | base64 --decode) > $KEYSTORE
        env:
          KEYSTORE: ./source/EduCATS.Android/educats-release.keystore
      
      - name: Build Number Variable Setup
        env:
          GITHUB_WORKFLOW_NUMBER: ${{ github.run_number }}
          BITRISE_LAST_BUILD_NUMBER: 860
        run: echo "APP_BUILD_NUMBER=$(($GITHUB_WORKFLOW_NUMBER+$BITRISE_LAST_BUILD_NUMBER))" >> $GITHUB_ENV          
      
      - name: Info.plist Version Update
        uses: damienaicheh/update-ios-version-info-plist-action@v1.0.0
        with:
          info-plist-path: ./source/EduCATS.iOS/Info.plist
          bundle-version: ${{ env.APP_BUILD_NUMBER }}
          bundle-short-version-string: ${{ env.APP_VERSION }}
          
      - name: AndroidManifest Version Update
        uses: damienaicheh/update-android-version-manifest-action@v1.0.0
        with:
          android-manifest-path: ./source/EduCATS.Android/Properties/AndroidManifest.xml
          version-name: ${{ env.APP_VERSION }}
          version-code: ${{ env.APP_BUILD_NUMBER }}
      
      - name: Artifacts Directory Setup
        run: mkdir ${{ env.ARTIFACTS_DIRECTORY }}
      
      - name: Android Build (apk + aab)
        run: |
          MSBuild /t:SignAndroidPackage /p:Configuration=Release /p:AndroidPackageFormat=apk /p:AndroidKeyStore=true /p:AndroidSigningKeyAlias='${{ secrets.ANDROID_KEYSTORE_ALIAS }}' /p:AndroidSigningKeyPass='${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}' /p:AndroidSigningKeyStore=$KEYSTORE_FILENAME /p:AndroidSigningStorePass='${{ secrets.ANDROID_KEYSTORE_PASSWORD }}' $PROJECT_PATH
          cp $APK_FILE_PATH ${{ env.ARTIFACTS_APK_PATH }}
          MSBuild /t:SignAndroidPackage /p:Configuration=Release /p:AndroidPackageFormat=aab /p:AndroidKeyStore=true /p:AndroidSigningKeyAlias='${{ secrets.ANDROID_KEYSTORE_ALIAS }}' /p:AndroidSigningKeyPass='${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}' /p:AndroidSigningKeyStore=$KEYSTORE_FILENAME /p:AndroidSigningStorePass='${{ secrets.ANDROID_KEYSTORE_PASSWORD }}' $PROJECT_PATH
          cp $AAB_FILE_PATH ${{ env.ARTIFACTS_AAB_PATH }}
        env:
          PROJECT_PATH: ./source/EduCATS.Android/EduCATS.Android.csproj
          KEYSTORE_FILENAME: educats-release.keystore
          APK_FILE_PATH: ./source/EduCATS.Android/bin/Release/by.bntu.educats-Signed.apk
          AAB_FILE_PATH: ./source/EduCATS.Android/bin/Release/by.bntu.educats-Signed.aab

      - name: iOS Build
        run: |
          MSBuild /t:Build /p:Configuration=Release /p:Platform=iPhone /p:BuildIpa=true $PROJECT_PATH
          cp $IPA_PATH ${{ env.ARTIFACTS_IPA_PATH }}
        env:
          PROJECT_PATH: ./source/EduCATS.iOS/EduCATS.iOS.csproj
          IPA_PATH: ./source/EduCATS.iOS/bin/iPhone/Release/EduCATS.iOS.ipa
          
      - name: Artifacts Upload
        uses: actions/upload-artifact@v2
        with:
          name: apps-artifacts
          path: ${{ env.ARTIFACTS_DIRECTORY }}
          
  deploy:
    runs-on: macos-latest
    environment: github-actions-release
    needs: build

    steps:
      - name: Artifacts Download
        uses: actions/download-artifact@v2
        with:
          name: apps-artifacts
          
      - name: AppStore Deploy
        run: |
          (echo ${{ secrets.APPSTORE_CONNECT_API_KEY_FILE_P8 }} | base64 --decode) > $AUTH_KEY
          xcrun altool --upload-app -f ${{ env.ARTIFACTS_IPA_PATH }} --type ios -u ${{ secrets.APPLE_ID }} -p ${{ secrets.APPLE_SPECIFIC_PASSWORD }}
        env:
          AUTH_KEY: ./AuthKey.p8
          
      - name: Google Play Deploy
        uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_API_JSON_PLAIN }}
          packageName: $BUNDLE_ID
          releaseFiles: ${{ env.ARTIFACTS_AAB_PATH }}
          track: beta
        env:
          BUNDLE_ID: by.bntu.educats
