name: release

on: [ push ]
#  push:
#    branches: [ master ]

#   workflow_dispatch:
  
env:
  APP_VERSION: 2.2.0

jobs:
  build:
    runs-on: macos-latest
    environment: guthub-actions

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Restore NuGet packages
        run: nuget restore ./source/EduCATS.sln
        
      - name: Setup iOS certificates
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.IOS_CERTIFICATE_APPSTORE }}
          p12-password: ${{ secrets.IOS_CERTIFICATE_APPSTORE_PASSWORD }}
          keychain: github-actions-xamarin
          keychain-password: ''
      
      - name: Setup iOS provisioning profiles
        uses: akiojin/install-provisioning-profile-github-action@v1.0
        with:
          base64: ${{ secrets.IOS_CERTIFICATE_APPSTORE_PASSWORD }}
          
      - name: Setup Android signing 
        run: (echo ${{ secrets.ANDROID_KEYSTORE }} | base64 — decode) > ./source/EduCATS.Android/educats-release.keystore
      
      - name: Get Github workflow build number
        env:
          GITHUB_WORKFLOW_NUMBER: ${{ github.run_number }}
        run: echo ::set-env name=APP_BUILD_NUMBER::$(($GITHUB_WORKFLOW_NUMBER+860))
      
      - name: Update iOS app version
        uses: damienaicheh/update-ios-version-info-plist-action@v1.0.0
        with:
          info-plist-path: ./source/EduCATS.iOS/Info.plist
          bundle-version: ${{ env.APP_VERSION }}
          bundle-short-version-string: $APP_BUILD_NUMBER
          
      - name: Update Android app version
        uses: damienaicheh/update-android-version-manifest-action@v1.0.0
        with:
          android-manifest-path: ./source/EduCATS.Android/Properties/AndroidManifest.xml
          version-code: $APP_BUILD_NUMBER
          version-name: ${{ env.APP_VERSION }}
        
      - name: Build iOS        
        run: MSBuild /t:Build /p:Configuration=Release /p:Platform=iPhone /p:BuildIpa=true ./source/EduCATS.iOS/EduCATS.iOS.csproj              
      
      - name: Build Android
        run: MSBuild /t:SignAndroidPackage /p:Configuration=Release /p:AndroidPackageFormat=apk /p:AndroidKeyStore=true /p:AndroidSigningKeyAlias=${{ secrets.ANDROID_KEYSTORE_ALIAS }} /p:AndroidSigningKeyPass=${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }} /p:AndroidSigningKeyStore=${{ secrets.ANDROID_KEYSTORE }} /p:AndroidSigningStorePass=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} ./source/EduCATS.Android/EduCATS.Android.csproj
