name: release

on: [ push ]
#  push:
#    branches: [ master ]

#   workflow_dispatch:
  
env:
  APP_VERSION: 2.2.0
  IOS_PROJECT_PATH: ./source/EduCATS.iOS/EduCATS.iOS.csproj
  ANDROID_PROJECT_PATH: ./source/EduCATS.Android/EduCATS.Android.csproj
  ANDROID_KEYSTORE: ./source/EduCATS.Android/educats-release.keystore
  ANDROID_KEYSTORE_FILE_NAME: educats-release.keystore

jobs:
  release:
    runs-on: macos-latest
    environment: github-actions-release

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Restore NuGet packages
        run: nuget restore ./source/EduCATS.sln
        
      - name: Setup iOS certificates
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.IOS_CERTIFICATE_APPSTORE }}
          p12-password: ${{ secrets.IOS_CERTIFICATE_APPSTORE_PASSWORD }}
          keychain: github-actions-xamarin
          keychain-password: ''
      
      - name: Setup iOS provisioning profiles
        uses: akiojin/install-provisioning-profile-github-action@v1.0
        with:
          base64: ${{ secrets.IOS_PROVISIONING_PROFILE_APPSTORE }}
          
      - name: Setup Android signing 
        run: (echo ${{ secrets.ANDROID_KEYSTORE_FILE }} | base64 --decode) > ${{ env.ANDROID_KEYSTORE }}
      
      - name: Get Github workflow build number
        env:
          GITHUB_WORKFLOW_NUMBER: ${{ github.run_number }}
        run: echo "APP_BUILD_NUMBER=$(($GITHUB_WORKFLOW_NUMBER+860))" >> $GITHUB_ENV
      
      - name: Update iOS app version
        uses: damienaicheh/update-ios-version-info-plist-action@v1.0.0
        with:
          info-plist-path: ./source/EduCATS.iOS/Info.plist
          bundle-version: ${{ env.APP_VERSION }}
          bundle-short-version-string: ${{ env.APP_BUILD_NUMBER }}
          
      - name: Update Android app version
        uses: damienaicheh/update-android-version-manifest-action@v1.0.0
        with:
          android-manifest-path: ./source/EduCATS.Android/Properties/AndroidManifest.xml
          version-name: ${{ env.APP_VERSION }}
          version-code: ${{ env.APP_BUILD_NUMBER }}
      
      - name: Build Android
        run: MSBuild /t:SignAndroidPackage /p:Configuration=Release /p:AndroidKeyStore=true /p:AndroidSigningKeyAlias='${{ secrets.ANDROID_KEYSTORE_ALIAS }}' /p:AndroidSigningKeyPass='${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}' /p:AndroidSigningKeyStore='${{ env.ANDROID_KEYSTORE_FILE_NAME }}' /p:AndroidSigningStorePass='${{ secrets.ANDROID_KEYSTORE_PASSWORD }}' ${{ env.ANDROID_PROJECT_PATH }}
  
      - name: Build iOS        
        run: MSBuild /t:Build /p:Configuration=Release /p:Platform=iPhone /p:BuildIpa=true ${{ env.IOS_PROJECT_PATH }}

      - if: always()
        run: ls ./source/./source/EduCATS.Android/obj
      - if: always()
        run: ls ./source/./source/EduCATS.iOS/obj
      - if: always()
        run: ls ./source/./source/EduCATS.Android/bin
      - if: always()
        run: ls ./source/./source/EduCATS.iOS/bin
      - if: always()
        run: ls ./source/./source/EduCATS.Android/bin/Release
      - if: always()
        run: ls ./source/./source/EduCATS.Android/bin/Debug
      - if: always()
        run: ls ./source/./source/EduCATS.Android/obj/Release
      - if: always()
        run: ls ./source/./source/EduCATS.Android/obj/Debug
      - if: always()
        run: ls ./source/./source/EduCATS.iOS/bin/Release
      - if: always()
        run: ls ./source/./source/EduCATS.iOS/bin/Debug
      - if: always()
        run: ls ./source/./source/EduCATS.iOS/obj/Release
      - if: always()
        run: ls ./source/./source/EduCATS.iOS/obj/Debug
        
